from typing import List, Dict, Any, Union

class QwenTokenizer:
    def __init__(self, tokenizer_dir: str = ...) -> None: ...
    def encode(self, text: str) -> List[int]: ...
    def decode(self, ids: List[int]) -> str: ...
    def __call__(self, texts: Union[str, List[str]], **kwargs: Any) -> Dict[str, List[List[int]]]: ...

__all__ = ["QwenTokenizer"]